application: wifi-location
version: 5
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /media
  static_dir: media
  
- url: /.*
  script: src/main.py




